[book]
authors = ["Freddie Haddad"]
language = "en"
src = "src"
title = "Fast Track to Rust"
description = "A course designed to get you going in Rust fast!"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/freddiehaddad/fast-track-to-rust"

[output.html.playground]
editable = true
line-numbers = true

[rust]
edition = "2021"
